# Generated by Django 4.0.3 on 2022-03-01 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportWow_app', '0003_team_stadium'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='SportWow_app.league'),
            preserve_default=False,
        ),
    ]
