# Generated by Django 4.0.3 on 2022-03-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportWow_app', '0010_alter_team_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
