# Generated by Django 4.0.3 on 2022-03-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportWow_app', '0011_alter_stadium_capacity_alter_team_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='goals_against',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='goals_for',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
