# Generated by Django 4.0.3 on 2022-03-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportWow_app', '0014_personalwatchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='attendance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
