# Generated by Django 4.0.3 on 2022-03-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportWow_app', '0018_remove_player_team_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
