# Generated by Django 4.0.3 on 2022-03-16 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('picture_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('picture_url', models.URLField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='SportWow_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('birth_date', models.DateField()),
                ('picture_url', models.URLField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='SportWow_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('capacity', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='SportWow_app.city')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('picture_url', models.URLField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('goals_for', models.IntegerField(blank=True, default=0, null=True)),
                ('goals_against', models.IntegerField(blank=True, default=0, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='SportWow_app.city')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='SportWow_app.country')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='SportWow_app.league')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='SportWow_app.stadium')),
            ],
        ),
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('red_cards', models.IntegerField(default=0)),
                ('appearances', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='SportWow_app.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='SportWow_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='SportWow_app.coach')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='SportWow_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalWatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('League', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='SportWow_app.league')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='SportWow_app.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('game_date', models.DateField()),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('attendance', models.IntegerField(blank=True, null=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='away_team', to='SportWow_app.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='home_team', to='SportWow_app.team')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='SportWow_app.country'),
        ),
    ]
