# Generated by Django 4.0.3 on 2022-03-16 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportWow_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='league',
        ),
    ]
