# Generated by Django 4.0.3 on 2022-03-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportWow_app', '0002_team_color1_team_color2'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
