# Generated by Django 4.0.3 on 2022-03-01 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportWow_app', '0002_player_picture_url_team_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='stadium',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='SportWow_app.stadium'),
            preserve_default=False,
        ),
    ]
