# Generated by Django 4.0.3 on 2022-03-16 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportWow_app', '0003_match_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='SportWow_app.league'),
        ),
    ]
