# Generated by Django 4.0.3 on 2022-03-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportWow_app', '0003_match_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
