# Generated by Django 4.0.3 on 2022-03-26 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportWow_app', '0004_alter_match_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalWatchList',
        ),
    ]
