# Generated by Django 4.0.3 on 2022-03-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportWow_app', '0005_team_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='capacity',
            field=models.CharField(default=None, max_length=6),
            preserve_default=False,
        ),
    ]
