# Generated by Django 4.0.3 on 2022-03-26 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SportWow_app', '0005_delete_personalwatchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='SportWow_app.match')),
            ],
        ),
        migrations.CreateModel(
            name='OrderedTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='SportWow_app.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
