# Generated by Django 4.0.3 on 2022-03-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportWow_app', '0006_ticket_orderedticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='picture_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
