# Generated by Django 4.0.3 on 2022-03-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportWow_app', '0007_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stadium',
            name='capacity',
            field=models.IntegerField(max_length=6),
        ),
    ]
