# Generated by Django 4.0.3 on 2022-03-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportWow_app', '0009_remove_match_score_match_away_score_match_home_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='points',
            field=models.IntegerField(blank=True, default=0, max_length=3, null=True),
        ),
    ]
