# Generated by Django 4.0.3 on 2022-03-29 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportWow_app', '0010_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='SportWow_app.city'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='SportWow_app.team'),
        ),
    ]
