# Generated by Django 4.0.3 on 2022-03-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportWow_app', '0012_alter_userprofile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_team',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
