# Generated by Django 4.0.3 on 2022-04-07 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SportWow_app', '0013_alter_userprofile_favorite_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='SportWow_app.city'),
        ),
        migrations.AlterField(
            model_name='team',
            name='color1',
            field=models.CharField(blank=True, default='white', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='color2',
            field=models.CharField(blank=True, default='black', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='stadium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='SportWow_app.stadium'),
        ),
    ]
