# Generated by Django 4.0.3 on 2022-03-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportWow_app', '0015_match_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplayer',
            name='appearances',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamplayer',
            name='assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamplayer',
            name='goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamplayer',
            name='red_cards',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamplayer',
            name='yellow_cards',
            field=models.IntegerField(default=0),
        ),
    ]
