# Generated by Django 4.0.3 on 2022-03-10 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportWow_app', '0017_player_team_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team_player',
        ),
    ]
